### ISSUE TITLE
'astropy' is a dependency?

### ISSUE THREAD

**Issue by dmilkie** [abcucberkeley/opticalaberrations#1]
It looks like 'astropy' is a dependency.  Should it appear in requirements.yml? (or requirements.txt....actually I'm also confused why there are two of these files and the contents are not the same)

**Comment by dmilkie** [comment]
Also, 'raster_geometry' is a dependency?

**Comment by dmilkie** [comment]
and 'zarr'

**Comment by thayerAlshaabi** [comment]
Yup! Both files should match. They're just out of date right now, I'll update that asap.

**Comment by thayerAlshaabi** [comment]
Updated!
