### ISSUE TITLE
--flipz flag is not referencing the flipz variable in test_ao.py

### ISSUE THREAD

**Issue by dmilkie** [abcucberkeley/opticalaberrations#2]
I think this is a typo in test_ao.py
https://github.com/abcucberkeley/opticalaberrations/blob/9db2f48627023d61bb676f5fb90e973cdaf2d751/src/test_ao.py#L67

should be:
` deskew += f" --flipz {flipz}" `
I'm kinda surprised that things are working, because as written I'm guessing that "10" would be converted to "true", when flipz was set to 'false".

**Comment by dmilkie** [comment]
Or, is it just the presence of --flipz that counts as "true" and there is no value (true/false) that should come after it?

**Comment by thayerAlshaabi** [comment]
Yup, you pass that flag if you want it to be on otherwise it's off by default. It doesn't care if you pass anything after it.

**Comment by dmilkie** [comment]
Sorry.  I was mentioning there was a typo, and proposing that this line should be changed to end with: `  if flipz else ""`.  I wanted to be aware, in case you had tests that relied upon the buggy code as written.
